Repository final-T/GlowGrow, pull requests merged in 2024-10, with the labels that each got.

#28 [FEAT] 예약 가능 시간 테이블 기능 구현 (기본 CRUD)
  reservation/.gitignore
  reservation/build.gradle
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateTimeSlotRequestDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/TimeSlotDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateTimeSlotRequestDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/config/JpaConfig.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/TimeSlot.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/CustomTimeSlotRepository.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/TimeSlotRepository.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/CustomTimeSlotRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/TimeSlotResponse.java
Labels: enhancement

#29 [FEAT] 프로모션 CRUD Search 구현 및 AOP로깅 기능 추가
  GlowGrow-common/src/main/java/com/tk/gg/common/aspect/LoggingAspectCommon.java
  GlowGrow-common/src/main/java/com/tk/gg/common/jpa/JpaConfig.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  promotion/src/main/java/com/tk/gg/promotion/PromotionApplication.java
  promotion/src/main/java/com/tk/gg/promotion/application/PromotionApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/PromotionRequestDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/PromotionResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/PromotionSearch.java
  promotion/src/main/java/com/tk/gg/promotion/domain/Coupon.java
  promotion/src/main/java/com/tk/gg/promotion/domain/CouponUser.java
  promotion/src/main/java/com/tk/gg/promotion/domain/Promotion.java
  promotion/src/main/java/com/tk/gg/promotion/domain/enums/CouponStatus.java
  promotion/src/main/java/com/tk/gg/promotion/domain/enums/DiscountType.java
  promotion/src/main/java/com/tk/gg/promotion/domain/enums/PromotionStatus.java
  promotion/src/main/java/com/tk/gg/promotion/domain/repository/PromotionRepositoryCustom.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/PromotionDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/PromotionRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/PromotionRepositoryImpl.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/PromotionController.java
Labels: enhancement

#32 [Fix] TimeSlot 관련 코드 수정
  reservation/src/main/java/com/tk/gg/reservation/ReservationApplication.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateTimeSlotRequestDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/TimeSlotDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateTimeSlotRequestDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/TimeSlot.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/TimeSlotRepositoryCustom.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/TimeSlotResponse.java
Labels: bug, enhancement

#33 [FEAT] 예약 기본 기능 CRUD,Search 구현
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/config/JpaConfig.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/ReservationRepositoryCustom.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/TimeSlotRepository.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/type/ReservationStatus.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReservationResponse.java
Labels: enhancement

#35 Feat/post read
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  post/src/main/java/com/tk/gg/post/PostApplication.java
  post/src/main/java/com/tk/gg/post/application/dto/PostSearchCondition.java
  post/src/main/java/com/tk/gg/post/application/dto/PostSearchResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/model/Post.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepository.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepositoryCustom.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
Labels: enhancement

#36 [FEAT] 프로모션 상태 스케쥴러 처리 및 쿠폰 생성 및 발급 기능 구현
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponCreateRequestDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponIssueRequestDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponIssueResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/scheduler/PromotionStatusScheduler.java
  promotion/src/main/java/com/tk/gg/promotion/application/serivce/CouponApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/application/serivce/PromotionApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/Coupon.java
  promotion/src/main/java/com/tk/gg/promotion/domain/CouponUser.java
  promotion/src/main/java/com/tk/gg/promotion/domain/Promotion.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/PromotionDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/PromotionRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/config/SchedulerConfig.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/PromotionRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/PromotionRepositoryImpl.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/PromotionController.java
Labels: enhancement

#38 [REFACTOR] 예약 - 예약타임슬롯 로직 검증 및 수정사항 반영
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/TimeSlotRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationStatusRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReservationResponse.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReservationServiceTest.java
Labels: bug, enhancement

#40 [FEAT] 게시판 좋아요 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  post/src/main/java/com/tk/gg/post/application/dto/LikeResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/LikeService.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/model/Like.java
  post/src/main/java/com/tk/gg/post/domain/model/Post.java
  post/src/main/java/com/tk/gg/post/domain/repository/LikeRepository.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepository.java
  post/src/main/java/com/tk/gg/post/presentation/controller/LikeController.java
  post/src/test/java/com/tk/gg/post/PostServiceTest.java
Labels: enhancement

#42 [FIX] Like 좋아요수 응답Dto 수정 및 리팩토링
  post/src/main/java/com/tk/gg/post/application/dto/LikeResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/LikeService.java
Labels: bug, enhancement

#43 [FEAT] 발급된 쿠폰 조회 및 사용 구현, 쿠폰 상태 스케줄러 처리
  gateway/src/main/resources/application.yml
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponUserResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/scheduler/PromotionAndCouponStatusScheduler.java
  promotion/src/main/java/com/tk/gg/promotion/application/serivce/CouponApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/CouponUser.java
  promotion/src/main/java/com/tk/gg/promotion/domain/enums/CouponStatus.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/PromotionRepository.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CoponUserController.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
Labels: enhancement

#47 [FEAT] 리뷰 및 평점 기본 CRUD 구현
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReviewDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReviewDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReviewWithReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReviewDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Review.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/ReviewRepositoryCustom.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReviewRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/ReviewSearchCondition.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReviewRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReviewResponse.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReviewWithReservationResponse.java
Labels: enhancement

#53 [FEAT] 회원가입, 로그인 및 security 관련 개발
  GlowGrow-common/build.gradle
  GlowGrow-common/src/main/java/com/tk/gg/common/response/GlobalExceptionResponse.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-security/GlowGrow-security.iml
  GlowGrow-security/HELP.md
  GlowGrow-security/build.gradle
  GlowGrow-security/gradlew
  GlowGrow-security/gradlew.bat
  GlowGrow-security/settings.gradle
  GlowGrow-security/src/main/java/com/tk/gg/security/GlowGrowSecurityApplication.java
  GlowGrow-security/src/main/java/com/tk/gg/security/config/GlowGrowSecurityConfiguration.java
  GlowGrow-security/src/main/java/com/tk/gg/security/config/UserInfoEncoder.java
  GlowGrow-security/src/main/java/com/tk/gg/security/filter/JwtAuthorizationFilter.java
  GlowGrow-security/src/main/java/com/tk/gg/security/handlers/CustomAccessDeniedHandler.java
  GlowGrow-security/src/main/java/com/tk/gg/security/handlers/CustomAuthenticationEntryPoint.java
  GlowGrow-security/src/main/java/com/tk/gg/security/jwt/JwtProvider.java
  GlowGrow-security/src/main/java/com/tk/gg/security/jwt/TokenInfo.java
  GlowGrow-security/src/main/java/com/tk/gg/security/jwt/TokenStatus.java
  GlowGrow-security/src/main/java/com/tk/gg/security/jwt/TokenableInfo.java
  GlowGrow-security/src/main/java/com/tk/gg/security/jwt/TokenableUser.java
  GlowGrow-security/src/main/java/com/tk/gg/security/user/AuthUser.java
  GlowGrow-security/src/main/java/com/tk/gg/security/user/AuthUserArgumentResolver.java
  GlowGrow-security/src/main/java/com/tk/gg/security/user/AuthUserInfo.java
  GlowGrow-security/src/main/java/com/tk/gg/security/user/AuthUserInfoImpl.java
  GlowGrow-security/src/main/java/com/tk/gg/security/user/SecurityArgumentConfig.java
  GlowGrow-security/src/main/resources/application.properties
  GlowGrow-security/src/main/resources/application.yml
  GlowGrow-security/src/main/resources/token-secret.properties
  auth/.gitignore
  auth/build.gradle
  auth/gradle/wrapper/gradle-wrapper.jar
  auth/gradle/wrapper/gradle-wrapper.properties
  auth/src/main/java/com/tk/gg/auth/AuthApplication.java
  auth/src/main/java/com/tk/gg/auth/application/dto/UserDto.java
  auth/src/main/java/com/tk/gg/auth/application/service/AuthService.java
  auth/src/main/java/com/tk/gg/auth/domain/model/User.java
  auth/src/main/java/com/tk/gg/auth/domain/repository/UserRepository.java
  auth/src/main/java/com/tk/gg/auth/domain/service/UserDomainService.java
  auth/src/main/java/com/tk/gg/auth/presentation/controller/AuthController.java
  auth/src/main/java/com/tk/gg/auth/presentation/request/LoginRequest.java
  auth/src/main/java/com/tk/gg/auth/presentation/request/SignUpRequest.java
  auth/src/main/java/com/tk/gg/auth/presentation/response/TokenInfoResponse.java
  auth/src/main/resources/application.properties
  auth/src/test/java/com/tk/gg/auth/AuthApplicationTests.java
  build.gradle
  settings.gradle
Labels: enhancement

#54 [FEAT] 게시판 조회시 댓글 리스트 기능 구현
  post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
  post/src/main/java/com/tk/gg/post/application/dto/PostSearchCondition.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
Labels: enhancement

#56 [FEAT] gateway swagger 통합 및 서비스 Config 설정
  GlowGrow-common/src/main/java/com/tk/gg/common/cors/WebConfig.java
  gateway/src/main/resources/application.yml
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/config/SwaggerConfig.java
  promotion/src/main/resources/application.yml
Labels: documentation, enhancement

#57 [FEAT] 예약 서비스 모듈 반환 메시지, 에러 enum 정의, 리뷰 생성 시 서비스 테스트 작성
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewServiceTest.java
Labels: enhancement

#58 [FEAT] Feign 호출을 통한 사용자 확인 API 개발
  GlowGrow-security/src/main/java/com/tk/gg/security/handlers/CustomAccessDeniedHandler.java
  GlowGrow-users/GlowGrow-users.iml
  GlowGrow-users/HELP.md
  GlowGrow-users/build.gradle
  GlowGrow-users/settings.gradle
  GlowGrow-users/src/main/java/com/tk/gg/users/GlowGrowUsersApplication.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/UserService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/UserRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserFeignController.java
  GlowGrow-users/src/main/resources/application.properties
  GlowGrow-users/src/main/resources/application.yml
  auth/build.gradle
  auth/src/main/resources/application.properties
  auth/src/main/resources/application.yml
Labels: enhancement

#61 [FEAT] 게시판_멀티미디어 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  post/build.gradle
  post/src/main/java/com/tk/gg/post/application/dto/MultiMediaSearchDto.java
  post/src/main/java/com/tk/gg/post/application/dto/MultimediaDto.java
  post/src/main/java/com/tk/gg/post/application/service/MultimediaService.java
  post/src/main/java/com/tk/gg/post/application/service/UploadService.java
  post/src/main/java/com/tk/gg/post/domain/model/Multimedia.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepository.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustom.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustomImpl.java
  post/src/main/java/com/tk/gg/post/domain/service/MultimediaDomainService.java
  post/src/main/java/com/tk/gg/post/domain/type/FileType.java
  post/src/main/java/com/tk/gg/post/infrastructure/S3UploadService.java
  post/src/main/java/com/tk/gg/post/lib/FileUtil.java
  post/src/main/java/com/tk/gg/post/presentation/controller/MultimediaController.java
Labels: enhancement

#62 [Fix] Post, Like, Comment DDD 서비스 분리
  post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/CommentService.java
  post/src/main/java/com/tk/gg/post/application/service/LikeService.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/model/Post.java
  post/src/main/java/com/tk/gg/post/domain/service/CommentDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/LikeDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/PostDomainService.java
Labels: enhancement

#66 [FEAT] 예약타임슬롯 security 적용, 유저 검증, 컨트롤러 단위 테스트 작성
  reservation/build.gradle
  reservation/src/main/java/com/tk/gg/reservation/ReservationApplication.java
  reservation/src/main/java/com/tk/gg/reservation/application/client/UserService.java
  reservation/src/main/java/com/tk/gg/reservation/application/client/UserServiceImpl.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/client/UserClient.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/ComponentScanConfig.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateTimeSlotRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/TimeSlotResponse.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/TimeSlotControllerTest.java
Labels: bug, enhancement

#67 [FEAT] 쿠폰 발급 동시성 문제 해결
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  promotion/build.gradle
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponCreateRequestDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponIssueRequestDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/scheduler/CouponStockSyncScheduler.java
  promotion/src/main/java/com/tk/gg/promotion/domain/Coupon.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/PromotionRepository.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/RedisRepository.java
  promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
Labels: enhancement

#68 [FEAT] 사용자 쿠폰 발급 비동기 처리
  promotion/build.gradle
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponIssueResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/messaging/CouponIssueEvent.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/messaging/CouponIssueEventHandler.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/messaging/CouponKafkaProducer.java
  promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
Labels: enhancement

#72 [FEAT] : 알림 기능 개발
  GlowGrow-common/src/main/java/com/tk/gg/common/enums/NotificationType.java
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/alarm/NotificationDto.java
  notification/.gitignore
  notification/build.gradle
  notification/gradle/wrapper/gradle-wrapper.jar
  notification/gradle/wrapper/gradle-wrapper.properties
  notification/gradlew
  notification/gradlew.bat
  notification/src/main/java/com/tk/gg/notification/NotificationApplication.java
  notification/src/main/java/com/tk/gg/notification/domain/model/Notification.java
  notification/src/main/java/com/tk/gg/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/tk/gg/notification/domain/service/NotificationDomainService.java
  notification/src/main/resources/application.yml
  notification/src/test/java/com/tk/gg/notification/NotificationApplicationTests.java
  settings.gradle
Labels: enhancement

#73 [FEAT] 예약 security 적용, 유저 검증, 컨트롤러 단위 테스트 작성
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReservationResponse.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
Labels: bug, enhancement

#74 [FEAT] 신고 기능 개발
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReportDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReportDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Report.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReportDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReportRepository.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReportController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReportRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReportResponse.java
Labels: documentation, enhancement

#75 [FEAT] Post, Multimedia, Comment 사용자 검증 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  post/build.gradle
  post/src/main/java/com/tk/gg/post/PostApplication.java
  post/src/main/java/com/tk/gg/post/application/client/UploadService.java
  post/src/main/java/com/tk/gg/post/application/client/UserService.java
  post/src/main/java/com/tk/gg/post/application/client/UserServiceImpl.java
  post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/CommentService.java
  post/src/main/java/com/tk/gg/post/application/service/LikeService.java
  post/src/main/java/com/tk/gg/post/application/service/MultimediaService.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/model/Comment.java
  post/src/main/java/com/tk/gg/post/domain/model/Like.java
  post/src/main/java/com/tk/gg/post/domain/model/Multimedia.java
  post/src/main/java/com/tk/gg/post/domain/model/Post.java
  post/src/main/java/com/tk/gg/post/domain/service/CommentDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/LikeDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/MultimediaDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/PostDomainService.java
  post/src/main/java/com/tk/gg/post/infrastructure/S3UploadService.java
  post/src/main/java/com/tk/gg/post/infrastructure/client/UserFeignClient.java
  post/src/main/java/com/tk/gg/post/presentation/controller/CommentController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/LikeController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/MultimediaController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
Labels: bug, enhancement

#80 [FEAT] 프로필 관련 개발
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  GlowGrow-users/build.gradle
  GlowGrow-users/src/main/java/com/tk/gg/users/GlowGrowUsersApplication.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/AwardDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/PreferLocationDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/PreferPriceDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/PreferStyleDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/ProfileDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/WorkExperienceDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/ProfileService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Award.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferLocation.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferPrice.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferStyle.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Profile.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/WorkExperience.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/AwardRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/PreferLocationRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/PreferPriceRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/PreferStyleRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/ProfileRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/profile/WorkExperienceRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/user/UserRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/ProfileDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/config/SecurityConfig.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/config/SwaggerConfig.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/repository/profile/ProfileQueryDslRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/repository/profile/ProfileQueryDslRepositoryImpl.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/ProfileController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/AwardRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/CreateProfileRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/LocationRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/PriceRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/ProfileRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/ProfileSearch.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/StyleRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/UpdateProfileRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/WorkExperienceRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/AwardResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/LocationResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/PriceResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/ProfilePageResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/ProfileResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/StyleResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/WorkExperienceResponse.java
  GlowGrow-users/src/main/resources/application.yml
Labels: enhancement

#81 [FEAT] 평가정보 관리 기능 1차 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/build.gradle
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CustomerGradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/GradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ProviderGradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ResultGradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/GradeService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Grade.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Report.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Review.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/GradeRepositoryCustom.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/GradeDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/ComponentScanConfig.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeForReservationEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeForReviewEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/ToUserKafkaProducer.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/GradeRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/GradeRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/GradeController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/GradeResponse.java
Labels: enhancement

#82 [FEAT] 채팅 서비스 생성 및 세팅
  chat/.gitignore
  chat/build.gradle
  chat/gradle/wrapper/gradle-wrapper.jar
  chat/gradle/wrapper/gradle-wrapper.properties
  chat/gradlew
  chat/gradlew.bat
  chat/src/main/java/com/tk/gg/chat/ChatApplication.java
  chat/src/main/resources/application.yml
  chat/src/test/java/com/tk/gg/chat/ChatApplicationTests.java
  settings.gradle
Labels: enhancement

#85 [FEAT] 결제 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/build.gradle
  payment/src/main/java/com/tk/gg/payment/PaymentApplication.java
  payment/src/main/java/com/tk/gg/payment/application/client/UserService.java
  payment/src/main/java/com/tk/gg/payment/application/client/UserServiceImpl.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentFailDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentRequestDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentResponseDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentSuccessCardDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentSuccessDto.java
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/type/PayType.java
  payment/src/main/java/com/tk/gg/payment/domain/type/PaymentStatus.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/client/UserFeignClient.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/config/TossPaymentConfig.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/controller/PaymentController.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/resources/static/paymentprepare.html
Labels: enhancement

#89 [FEAT] 예약, 리뷰 -> 평가정보 반영 카프카 이벤트 , 평가정보 -> 유저 둥급 반영 카프카 이벤트 작성
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/grade/GradeForReservationEventDto.java
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/grade/GradeForReviewEventDto.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReviewDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CustomerGradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/GradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ProviderGradeDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/GradeService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Grade.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/GradeDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeForReservationEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeKafkaListener.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeKafkaProducer.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/GradeRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReviewRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/validation/RatingConstraint.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/GradeResponse.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewServiceTest.java
Labels: enhancement

#90 [FEAT] : User module
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-users/build.gradle
  GlowGrow-users/src/main/java/com/tk/gg/users/GlowGrowUsersApplication.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/client/ReservationClient.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/datainitializer/GradeDataInitializer.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/UserService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/GradeRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/GradeDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/messaging/GradeKafkaListener.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/UpdateUserInfoRequest.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/GradeResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/ResultGradeDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/UserResponse.java
Labels: enhancement

#92 [FIX] 예약 엔티티 `price` 필드 추가 및 관련 코드 수정
  reservation/src/main/java/com/tk/gg/reservation/application/dto/CreateReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/ReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/ComponentScanConfig.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/response/ReservationResponse.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewServiceTest.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
Labels: bug, enhancement

#93 [FEAT] : 회원등급 관련 개발
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/client/ReservationClient.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/datainitializer/GradeDataInitializer.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/CustomerGradeEvaluationDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/GradeDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/ProviderGradeEvaluationDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/dto/UserGradeDto.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/GradeService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/ReservationService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/GradeRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/repository/grade/UserGradeRepository.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/GradeDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/type/UserGradeType.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/config/SecurityConfig.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/messaging/GradeKafkaListener.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/UserController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/GradeResponse.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/response/UserGradeResponse.java
Labels: enhancement

#94 [FEAT] Reservation 모듈 path 별 권한 설정
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/SecurityConfig.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/GradeController.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReviewControllerTest.java
Labels: enhancement

#95 [FEAT] : Notification module
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/alarm/KafkaNotificationDto.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  notification/build.gradle
  notification/src/main/java/com/tk/gg/notification/NotificationApplication.java
  notification/src/main/java/com/tk/gg/notification/application/client/UserClient.java
  notification/src/main/java/com/tk/gg/notification/application/dto/NotificationDto.java
  notification/src/main/java/com/tk/gg/notification/application/service/NotificationService.java
  notification/src/main/java/com/tk/gg/notification/application/service/UserService.java
  notification/src/main/java/com/tk/gg/notification/domain/model/Notification.java
  notification/src/main/java/com/tk/gg/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/tk/gg/notification/domain/service/NotificationDomainService.java
  notification/src/main/java/com/tk/gg/notification/infra/config/SecurityConfig.java
  notification/src/main/java/com/tk/gg/notification/infra/config/SwaggerConfig.java
  notification/src/main/java/com/tk/gg/notification/presentation/controller/NotificationController.java
  notification/src/main/java/com/tk/gg/notification/presentation/response/NotificationResponse.java
Labels: enhancement

#97 feat : 모듈 수정
  GlowGrow-kafka/GlowGrow-kafka.iml
  GlowGrow-kafka/HELP.md
  GlowGrow-kafka/settings.gradle
  GlowGrow-users/build.gradle
  GlowGrow-users/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  notification/build.gradle
  notification/src/main/java/com/tk/gg/notification/infra/config/SecurityConfig.java
  notification/src/main/resources/application.yml
Labels: enhancement

#99 [FEAT] : s3
  GlowGrow-common/build.gradle
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/FileUtil.java
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/S3UploadService.java
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/UploadService.java
Labels: enhancement

#100 [FEAT] 예약, 리뷰, 신고 카프카 관련 코드 추가 및 리팩토링
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/grade/GradeForReportEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/type/ReservationStatus.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/SchedulerConfig.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeKafkaProducer.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/NotificationKafkaProducer.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepository.java
Labels: enhancement

#102 [FEAT] 결제 환불 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentCancelDto.java
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/application/service/RefundService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Refund.java
  payment/src/main/java/com/tk/gg/payment/domain/service/RefundDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/type/PaymentStatus.java
  payment/src/main/java/com/tk/gg/payment/domain/type/RefundType.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/controller/RefundController.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/RefundRepository.java
  payment/src/main/resources/static/paymentprepare.html
Labels: enhancement

#104 [FEAT] 사용자 결제 취소 기능 구현
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/type/PaymentStatus.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/controller/PaymentController.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/resources/static/paymentprepare.html
Labels: enhancement

#106 [FIX] S3 Bean 조건부 활성화
  GlowGrow-common/build.gradle
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/S3UploadService.java
Labels: bug, enhancement

#108 [BUG] 사용자 결제 취소 데이터 다중 -> 단일 결과 반환 수정
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
Labels: bug

#114 [FEAT] 예약 모듈 스웨거 설정
  gateway/src/main/resources/application.yml
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReportDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/SwaggerConfig.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/GradeController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReportController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReviewController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationStatusRequest.java
  reservation/src/main/resources/application.yml
Labels: enhancement

#115 [FEAT] 정산 기능 구현
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDto.java
  payment/src/main/java/com/tk/gg/payment/application/scheduler/SettlementScheduler.java
  payment/src/main/java/com/tk/gg/payment/application/service/SettlementService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Refund.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Settlement.java
  payment/src/main/java/com/tk/gg/payment/domain/repository/SettlementRepositoryCustom.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/type/SettlementStatus.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepositoryImpl.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/RefundController.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/SettlementController.java
Labels: enhancement

#117 fix : controller url 변경
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/ProfileController.java
Labels: bug

#120 [Feat] 각 서비스 Docker 파일
  GlowGrow-common/Dockerfile
  auth/Dockerfile
  chat/Dockerfile
  eureka/Dockerfile
  gateway/Dockerfile
  notification/Dockerfile
  payment/Dockerfile
  post/Dockerfile
  promotion/Dockerfile
  reservation/Dockerfile
Labels: enhancement

#121 [FEAT] 개발 환경 프로필 분리
  .gitignore
  GlowGrow-users/src/main/resources/application-local.yml
  GlowGrow-users/src/main/resources/application-prod.yml
  GlowGrow-users/src/main/resources/application.yml
  auth/gradlew
  auth/gradlew.bat
  auth/src/main/resources/application-local.yml
  auth/src/main/resources/application-prod.yml
  auth/src/main/resources/application.yml
  chat/src/main/resources/application-local.yml
  chat/src/main/resources/application-prod.yml
  chat/src/main/resources/application.yml
  eureka/src/main/resources/application-local.yml
  eureka/src/main/resources/application-prod.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/application.yml
  notification/src/main/resources/application-local.yml
  notification/src/main/resources/application-prodl.yml
  notification/src/main/resources/application.yml
  payment/src/main/resources/application-local.yml
  payment/src/main/resources/application-prod.yml
  payment/src/main/resources/application.yml
  post/src/main/resources/application-local.yml
  post/src/main/resources/application-prod.yml
  post/src/main/resources/application.yml
  promotion/src/main/resources/application-local.yml
  promotion/src/main/resources/application-prod.yml
  promotion/src/main/resources/application.yml
  reservation/src/main/resources/application-local.yml
  reservation/src/main/resources/application-prod.yml
  reservation/src/main/resources/application.yml
Labels: enhancement

#123 [FEAT] CI/CD 관련 파일 작성
  .github/workflows/gradle.yml
  docker-compose.yml
  dockerTagAndPush.sh
Labels: enhancement

#127 [FEAT] 모니터링 시스템 구축
  auth/src/main/resources/application-prod.yml
  auth/src/main/resources/logback.xml
  chat/src/main/resources/application-prod.yml
  chat/src/main/resources/logback.xml
  payment/src/main/resources/application-prod.yml
  payment/src/main/resources/logback.xml
  post/src/main/resources/application-prod.yml
  post/src/main/resources/logback.xml
  promotion/src/main/resources/application-prod.yml
  promotion/src/main/resources/logback.xml
Labels: enhancement

#128 Feat: 모니터링 의존성 추가 및 yml 설정
  GlowGrow-common/build.gradle
  GlowGrow-users/src/main/resources/application-prod.yml
  GlowGrow-users/src/main/resources/application.yml
  GlowGrow-users/src/main/resources/logback.xml
  eureka/build.gradle
  eureka/src/main/resources/application-prod.yml
  eureka/src/main/resources/logback.xml
  gateway/build.gradle
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/logback.xml
  notification/src/main/resources/application-prod.yml
  notification/src/main/resources/logback.xml
  reservation/src/main/resources/application-prod.yml
  reservation/src/main/resources/logback.xml
Labels: enhancement

#131 [FEAT] 결제 : 서버 사이드 렌더링으로 변경
  payment/build.gradle
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentRequestDto.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
  payment/src/main/resources/logback.xml
  payment/src/main/resources/templates/payment-prepare.html
  payment/src/main/resources/templates/payment-success.html
  post/src/main/resources/logback.xml
Labels: bug, enhancement

#134 유저 모듈 에러 수정
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  GlowGrow-users/src/main/java/com/tk/gg/users/application/datainitializer/GradeDataInitializer.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/GradeDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/ProfileDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/ProfileController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/UserController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/request/ProfileSearch.java
  GlowGrow-users/src/main/resources/application-local.yml
  GlowGrow-users/src/main/resources/application.yml
Labels: bug, enhancement

#137 [FEAT] 프로모션 Security 추가 및 유저 연결, 검증
  promotion/build.gradle
  promotion/src/main/java/com/tk/gg/promotion/application/serivce/PromotionApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/PromotionDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/config/SecurityConfig.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CoponUserController.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/PromotionController.java
  promotion/src/main/resources/application-local.yml
  promotion/src/main/resources/application-prod.yml
  promotion/src/main/resources/logback.xml
  promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
Labels: enhancement

#139 [BUG] local 환경에서 로그 안뜨는 버그 수정
  GlowGrow-users/src/main/resources/logback.xml
  auth/src/main/resources/logback.xml
  docker-compose-local.yml
  docker/docker-compose-monitor.yml
  eureka/src/main/resources/logback.xml
  gateway/src/main/resources/logback.xml
  init-mongo.js
  init.sql
  notification/src/main/resources/logback.xml
Labels: bug

#140 [FEAT] 요청 객체 유효성 검증 에러 핸들러 작성
  GlowGrow-common/src/main/java/com/tk/gg/common/response/GlobalExceptionResponse.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlobalExceptionHandler.java
Labels: enhancement

#142 [FiIX] : user
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Award.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Grade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferLocation.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferPrice.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/PreferStyle.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Profile.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/UserGrade.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/WorkExperience.java
  auth/src/main/java/com/tk/gg/auth/domain/repository/UserRepository.java
  auth/src/main/java/com/tk/gg/auth/domain/service/UserDomainService.java
  build.gradle
Labels: bug

#145 [FEAT] 정산 세부사항 기능 구현 및 결제, 정산 리팩토링
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentResponseDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDetailDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/SettlementDto.java
  payment/src/main/java/com/tk/gg/payment/application/service/SettlementService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Settlement.java
  payment/src/main/java/com/tk/gg/payment/domain/model/SettlementDetail.java
  payment/src/main/java/com/tk/gg/payment/domain/repository/PaymentRepositoryCustom.java
  payment/src/main/java/com/tk/gg/payment/domain/repository/SettlementDetailCustom.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDetailDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDomainService.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementDetailRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementDetailRepositoryImpl.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/SettlementRepositoryImpl.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/SettlementController.java
Labels: bug, enhancement

#146 [FEAT] 예약 모듈 - 결제 카프카 이벤트 작성, 리팩토링
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentForReservationEventDto.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/src/main/java/com/tk/gg/reservation/application/dto/UpdateReservationDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReportService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/TimeSlotService.java
  reservation/src/main/java/com/tk/gg/reservation/application/util/ReservationUserCheck.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/type/ReservationStatus.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/GradeKafkaListener.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/PaymentKafkaProducer.java
  reservation/src/main/resources/application-prod.yml
Labels: enhancement

#147 [Feat] : multimedia
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/FileUtil.java
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/S3UploadService.java
  GlowGrow-common/src/main/java/com/tk/gg/common/s3/UploadService.java
  multimedia/.gitignore
  multimedia/build.gradle
  multimedia/gradle/wrapper/gradle-wrapper.jar
  multimedia/gradle/wrapper/gradle-wrapper.properties
  multimedia/gradlew
  multimedia/gradlew.bat
  multimedia/src/main/java/com/tk/gg/multimedia/MultimediaApplication.java
  multimedia/src/main/java/com/tk/gg/multimedia/application/dto/MultimediaDto.java
  multimedia/src/main/java/com/tk/gg/multimedia/application/service/MultimediaService.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/model/Multimedia.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/repository/MultiMediaRepository.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/service/MultimediaDomainService.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/service/S3Service.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/type/FileType.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/type/FileUploadType.java
  multimedia/src/main/java/com/tk/gg/multimedia/infra/config/AmazonS3BucketProperties.java
  multimedia/src/main/java/com/tk/gg/multimedia/infra/config/SecurityConfig.java
  multimedia/src/main/java/com/tk/gg/multimedia/infra/config/SwaggerConfig.java
  multimedia/src/main/java/com/tk/gg/multimedia/infra/config/util/GlowGrowFileUtil.java
  multimedia/src/main/java/com/tk/gg/multimedia/presenation/controller/MultimediaController.java
  multimedia/src/main/java/com/tk/gg/multimedia/presenation/response/UploadResponse.java
  multimedia/src/main/resources/application-local.yml
  multimedia/src/main/resources/application-prod.yml
  multimedia/src/main/resources/application.yml
  multimedia/src/main/resources/logback.xml
  multimedia/src/test/java/com/tk/gg/multimedia/MultimediaApplicationTests.java
  settings.gradle
Labels: enhancement

#149 [Bug] 배포 환경, local환경 Redis 설정 문제 해결
  GlowGrow-redis/src/main/java/com/tk/gg/redis/config/RedisConfig.java
  GlowGrow-redis/src/main/resources/application.yml
  promotion/src/main/resources/application-local.yml
Labels: bug

#152 Fix: 예약 모듈 결제 카프카 이벤트 DTO 수정
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentForReservationEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
Labels: enhancement

#153 [FEAT] 완료예약 리뷰 알림 스케줄러 1차 작성
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  reservation/build.gradle
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewNotifyScheduler.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/TimeSlotDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/NotificationKafkaProducer.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReviewRepository.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/CreateReviewRequest.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/UpdateReservationRequest.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewNotifySchedulerTest.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
  reservation/src/test/resources/application-test.yml
Labels: enhancement

#155 [FEAT] 예약 전체 조회 시 검색 기능 추가 및 수정
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentForReservationEventDto.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/repository/ReservationRepositoryCustom.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/TimeSlotController.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/request/ReservationSearchCondition.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReservationServiceTest.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
Labels: enhancement

#156 [FEAT] 채팅방 생성 및 메시지 전송 기능 구현
  chat/build.gradle
  chat/src/main/java/com/tk/gg/chat/ChatApplication.java
  chat/src/main/java/com/tk/gg/chat/application/dto/ChatMessageDto.java
  chat/src/main/java/com/tk/gg/chat/application/service/ChatApplicationService.java
  chat/src/main/java/com/tk/gg/chat/application/service/ChatMessageConsumer.java
  chat/src/main/java/com/tk/gg/chat/application/service/ChatMessageService.java
  chat/src/main/java/com/tk/gg/chat/domain/ChatMessage.java
  chat/src/main/java/com/tk/gg/chat/domain/ChattingPartcipant.java
  chat/src/main/java/com/tk/gg/chat/domain/ChattingRoom.java
  chat/src/main/java/com/tk/gg/chat/domain/service/ChatDomainService.java
  chat/src/main/java/com/tk/gg/chat/infrastructure/config/WebSocketConfig.java
  chat/src/main/java/com/tk/gg/chat/infrastructure/repository/ChatMessageRepository.java
  chat/src/main/java/com/tk/gg/chat/infrastructure/repository/ChattingRoomRepository.java
  chat/src/main/java/com/tk/gg/chat/presentation/ChatController.java
  chat/src/main/java/com/tk/gg/chat/presentation/ChattingRoomCreateRequsetDto.java
  chat/src/main/java/com/tk/gg/chat/presentation/ChattingRoomResponseDto.java
  chat/src/main/resources/application-local.yml
  chat/src/main/resources/application-prod.yml
  chat/src/main/resources/application.yml
  chat/src/main/resources/logback.xml
  gateway/src/main/resources/application.yml
Labels: enhancement

#158 [FEAT] 사용자 쿠폰 사용 및 사용자 쿠폰 리스트 조회 수정
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/repository/CouponUserRepository.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CoponUserController.java
Labels: enhancement

#160 [FEAT] 쿠폰생성자 권한에 따른 쿠폰 code 생성 및 사용자 쿠폰 리스트 반환시 쿠폰 code 반환 수정
  promotion/build.gradle
  promotion/src/main/java/com/tk/gg/promotion/application/dto/CouponUserResponseDto.java
  promotion/src/main/java/com/tk/gg/promotion/application/serivce/CouponApplicationService.java
  promotion/src/main/java/com/tk/gg/promotion/domain/service/CouponDomainService.java
  promotion/src/main/java/com/tk/gg/promotion/presentation/controller/CouponController.java
  promotion/src/test/java/com/tk/gg/promotion/CouponIssuanceTest.java
Labels: enhancement

#161 [FEAT] common 모듈 response Dto 수정
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/coupon/CouponUserResponseDto.java
Labels: enhancement

#163 [FEAT] 결제 로직 변경 및 결제 검색 api 추가
  GlowGrow-common/src/main/java/com/tk/gg/common/kafka/payment/PaymentReservationResponseDto.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/build.gradle
  payment/src/main/java/com/tk/gg/payment/application/client/CouponService.java
  payment/src/main/java/com/tk/gg/payment/application/client/CouponServiceImpl.java
  payment/src/main/java/com/tk/gg/payment/application/client/ReservationService.java
  payment/src/main/java/com/tk/gg/payment/application/client/ReservationServiceImpl.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentRequestDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentResponseDto.java
  payment/src/main/java/com/tk/gg/payment/application/dto/PaymentSearchCondition.java
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/application/service/RefundService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Payment.java
  payment/src/main/java/com/tk/gg/payment/domain/repository/PaymentRepositoryCustom.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PaymentDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/type/CouponType.java
  payment/src/main/java/com/tk/gg/payment/domain/type/PayType.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/client/CouponFeignClient.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/client/ReservationFeignClient.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepository.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
  payment/src/main/resources/templates/payment-prepare.html
  promotion/src/main/java/com/tk/gg/promotion/infrastructure/config/SecurityConfig.java
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/messaging/PaymentKafkaProducer.java
Labels: bug, enhancement

#164 [FEAT] 정산 스케줄러 등록 및 쿠폰 유무, 종류에 따른 정산금 처리
  payment/src/main/java/com/tk/gg/payment/PaymentApplication.java
  payment/src/main/java/com/tk/gg/payment/application/scheduler/AutomatedSettlementScheduler.java
  payment/src/main/java/com/tk/gg/payment/application/scheduler/SettlementScheduler.java
  payment/src/main/java/com/tk/gg/payment/domain/model/Settlement.java
  payment/src/main/java/com/tk/gg/payment/domain/model/SettlementDetail.java
  payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDetailDomainService.java
  payment/src/main/java/com/tk/gg/payment/domain/service/SettlementDomainService.java
Labels: enhancement

#167 [FEAT] 예약의 서비스 제공자에 대한 쿠폰만 사용 가능하도록 수정
  payment/src/main/resources/templates/payment-prepare.html
Labels: enhancement

#168 [FEAT] 결제 요청 저장 및 알람 발송
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  payment/src/main/java/com/tk/gg/payment/application/service/PaymentService.java
  payment/src/main/java/com/tk/gg/payment/domain/model/PendingPaymentRequest.java
  payment/src/main/java/com/tk/gg/payment/domain/repository/PendingPaymentRequestRepository.java
  payment/src/main/java/com/tk/gg/payment/domain/service/PendingPaymentRequestDomainService.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/messaging/NotificationPaymentKafkaProducer.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/messaging/PaymentKafkaListener.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
Labels: enhancement

#170 [REFACTOR] 예약 모듈 리팩토링
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReviewNotifyScheduler.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Reservation.java
  reservation/src/main/java/com/tk/gg/reservation/domain/model/Review.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReviewDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepository.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  reservation/src/test/java/com/tk/gg/reservation/application/service/ReviewNotifySchedulerTest.java
  reservation/src/test/java/com/tk/gg/reservation/presentation/controller/ReservationControllerTest.java
Labels: enhancement

#171 [Feat, Fix] user
  GlowGrow-users/src/main/java/com/tk/gg/users/application/service/UserService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/Profile.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/model/User.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/ProfileDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/domain/service/UserDomainService.java
  GlowGrow-users/src/main/java/com/tk/gg/users/infra/repository/profile/ProfileQueryDslRepositoryImpl.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/ProfileController.java
  GlowGrow-users/src/main/java/com/tk/gg/users/presenation/controller/UserController.java
  auth/src/main/java/com/tk/gg/auth/domain/service/UserDomainService.java
Labels: bug, enhancement

#173 [FEAT] S3 모듈 분리에 따른 로직 변경
  GlowGrow-common/src/main/java/com/tk/gg/common/response/ResponseMessage.java
  GlowGrow-common/src/main/java/com/tk/gg/common/response/exception/GlowGlowError.java
  gateway/src/main/resources/application.yml
  multimedia/src/main/java/com/tk/gg/multimedia/application/service/MultimediaService.java
  multimedia/src/main/java/com/tk/gg/multimedia/domain/service/S3Service.java
  post/src/main/java/com/tk/gg/post/application/dto/MultiMediaSearchDto.java
  post/src/main/java/com/tk/gg/post/application/dto/MultimediaDto.java
  post/src/main/java/com/tk/gg/post/application/dto/PostFileDto.java
  post/src/main/java/com/tk/gg/post/application/dto/PostResponseDto.java
  post/src/main/java/com/tk/gg/post/application/dto/PostSearchResponseDto.java
  post/src/main/java/com/tk/gg/post/application/service/MultimediaService.java
  post/src/main/java/com/tk/gg/post/application/service/PostFileService.java
  post/src/main/java/com/tk/gg/post/application/service/PostService.java
  post/src/main/java/com/tk/gg/post/domain/model/Multimedia.java
  post/src/main/java/com/tk/gg/post/domain/model/Post.java
  post/src/main/java/com/tk/gg/post/domain/model/PostFile.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepository.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustom.java
  post/src/main/java/com/tk/gg/post/domain/repository/MultimediaRepositoryCustomImpl.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostFileRepository.java
  post/src/main/java/com/tk/gg/post/domain/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/tk/gg/post/domain/service/MultimediaDomainService.java
  post/src/main/java/com/tk/gg/post/domain/service/PostFileDomainService.java
  post/src/main/java/com/tk/gg/post/domain/type/FileType.java
  post/src/main/java/com/tk/gg/post/presentation/controller/MultimediaController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostFileController.java
Labels: bug, enhancement

#176 [FEAT] 게시글 좋아요 동시성 테스트 코드 수정
  post/build.gradle
  post/src/test/java/com/tk/gg/post/PostServiceTest.java
Labels: bug, enhancement

#177 [FIX] 예약 모듈 path 별 권한 수정
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/tk/gg/reservation/domain/service/ReservationDomainService.java
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/config/SecurityConfig.java
  reservation/src/main/java/com/tk/gg/reservation/presentation/controller/ReservationController.java
Labels: bug, enhancement

#178 [FIX] 예약 업데이트 시 예약슬롯 시간 비교 검증 추가
  reservation/src/main/java/com/tk/gg/reservation/application/service/ReservationService.java
Labels: bug, enhancement

#180 [FEAT] Swagger 어노테이션 적용 및 SecurityConfig 수정
  payment/src/main/java/com/tk/gg/payment/application/service/SettlementService.java
  payment/src/main/java/com/tk/gg/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/RefundController.java
  payment/src/main/java/com/tk/gg/payment/presentation/controller/SettlementController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/CommentController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostController.java
  post/src/main/java/com/tk/gg/post/presentation/controller/PostFileController.java
Labels: bug, enhancement

#182 [FEAT] SwaggerConfig 추가
  payment/src/main/java/com/tk/gg/payment/infrastructure/config/SwaggerConfig.java
  post/src/main/java/com/tk/gg/post/infrastructure/config/SwaggerConfig.java
Labels: enhancement

#189 [FEAT] Post Swagger-ui 추가
  post/src/main/resources/application-prod.yml
Labels: enhancement

#191 [FIX] 예약 페이징 쿼리 join 삭제
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
Labels: enhancement

#192 Dev
  GlowGrow-security/README.md
  README.md
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  reservation/src/main/java/com/tk/gg/reservation/infrastructure/repository/ReservationRepositoryImpl.java
Labels: documentation
